UPDATE readme
IIM-Creative-Technology/nodejs-A4IWM2-042022 pull request #2
Opened 2022-04-25 11:43 UTC by Sharcan

2022-04-25 14:42 UTC, MathiasGilles approved these changes

2022-04-26 07:05 UTC, alland07 requested changes
Il faudrait modifier le sommaire également je pense afin d'implémenter cette partie.

2022-04-26 07:18 UTC, SouchetJulie requested changes

2022-04-26 07:18 UTC, SouchetJulie commented on README.md
> +
Autant rajouter la commande pour utiliser nodemon à la suite non ? ;)
<hr>

nodemon permet de faciliter le développement en relançant automatiquement le serveur lors de modifications des fichiers sources. On peut l'ajouter aux scripts npm:
```json
"scripts": {
 "dev": "nodemon <nom_du_fichier_principal>"
}
```

Puis le lancer avec `npm run dev`

2022-04-27 06:52 UTC, SouchetJulie approved these changes

2022-04-27 09:09 UTC, alland07 approved these changes

2022-04-27 12:06 UTC, EidanU approved these changes

2022-04-27 14:02 UTC, AntoineDrsl approved these changes
nice

2022-04-27 14:03 UTC, merged